### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by 1valdis** [1valdis/heavensat-web#1]
For the initial release to be complete, the app must be minimally viable and useful. It should answer the question: **which satellite did I see at that time in that place of the sky?**
This leads to such basic things, by priority highest to lowest:
- [x] Controls: zoom, pan
- [x] Determine location based on GPS
- [ ] Set location to custom coordinates; have multiple locations; store locations between sessions (along with other upcoming settings)
- [ ] Show stars, constellations, solar system bodies at a given location for a given time.
- [ ] Have good time controls with hotkeys: ability to set arbitrary date and time, set current datetime, step forward and backward with hotkeys (initially fixed to 5 seconds, in future - be able to set the specific step).
- [x] Show satellites with their names.
- [ ] Show plain satellite trajectory (time markers to be done later)
- [ ] Show if the satellite is in shadow, using different color.
- [ ] Be able to filter satellites based on height, orbit parameters, shadow status etc.
- [ ] Show info about a selected satellite: apogee, perigee, height
- [x] Show sky as a gradient depending on the sun position: people like beautiful stuff
- [ ] Show alt/az and ra/dec under the cursor

What I think follows after answering that question is: **How do I see that satellite again? If it flared, how do I see the flare again?**
- [ ] "Favourite" satellites
- [ ] Calculations: calculate passes of favourite satellites, or a given satellite from the sky tab
- [ ] Mirrors: Determine sun-satellite-observer angle and mirror position (off-nadir and off-speed-vector angle); save and share it; calculate flares based on known mirrors.

Answering these most basic questions, I should keep UX, extensibility and flexibility in mind. That means:
- [ ] Settings page. Change star size, satellite appearance and font size
- [ ] Update space-track satellite bases automatically: use Github Actions for that
- [ ] Load third party satellite bases
- [ ] Load on demand or automatically on zoom-in larger star catalogs: Tycho-2 planned for that
- [ ] Be able to work completely offline with minimum impact on functionality
- [ ] More useful stuff drawn: azimuthal and equatorial grids; world directions; Earth shadow on a given height (useful for geostationary satellites)
- [ ] Measure angular size between points on the sky (useful for aided eye observers)

And let's not forget about known issues:
- [ ] App periodically freezes for ~100ms, looks like because of some misuse of WebGL2?
- [ ] Star color looks different on different machines. Remake calculation of color based on B-V index.

This is to be easily changed based on the community input. This issue tracks current state of the app and priorities. The priorities here don't correspond exactly to what I'm up to; that usually depends on my mood 🤣 If nobody from the community requests otherwise.
